name: Build Pure-Data Linux

on: [workflow_dispatch, workflow_call]

jobs:
  # ==========================
  # Pure-Data Build
  # ==========================

  # System:         Linux
  # Architecture:   Pure Data
  pd_build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Pure-Data
      uses: actions/checkout@v4
      with:
        repository: 'pure-data/pure-data'
        path: 'pd'
    - name: Check out mdeGranular
      uses: actions/checkout@v4
      with:
        path: 'mde'
    - name: Install system libraries
      run: sudo apt-get install build-essential libasound2-dev cmake
    - name: Build and Install Pure-Data
      run: |
        cd $GITHUB_WORKSPACE/pd
        ./autogen.sh
        ./configure --enable-libpd
        make
        sudo make install
    - name: Build and Install mdeGranular
      run: |
        cd $GITHUB_WORKSPACE/mde
        cmake -G "Unix Makefiles" -B builds/cmake -DCMAKE_FIND_DEBUG_MODE=TRUE -DMDE_TARGET_SDK_PATH=$GITHUB_WORKSPACE/pd -DCMAKE_VERBOSE_MAKEFILE=TRUE -S .
        cd builds/cmake
        make
    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: mdeGranular~.pd_linux
        path: ${{ github.workspace }}/mde/builds/cmake/mdeGranular~.pd_linux